# Generated by Django 2.0.6 on 2018-09-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_auto_20180903_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mineral',
            options={},
        ),
    ]
