# Generated by Django 2.1 on 2018-08-29 20:52

from django.db import IntegrityError
from django.db import migrations, transaction

import json


def make_mineral_dict(mineral):
    fields = {
        'name': None,
        'image filename': None,
        'image caption': None,
        'category': None,
        'formula': None,
        'strunz classification': None,
        'crystal system': None,
        'unit cell': None,
        'color': None,
        'crystal symmetry': None,
        'cleavage': None,
        'mohs scale hardness': None,
        'luster': None,
        'streak': None,
        'diaphaneity': None,
        'optical properties': None,
        'refractive index': None,
        'crystal habit': None,
        'specific gravity': None
    }
    for key, value in mineral.items():
        fields[key] = value
    return fields


def add_minerals_to_database(apps, schema_editor):
    Mineral = apps.get_model("minerals", "Mineral")
    with open('data/minerals.json', encoding='utf-8') as file:
        minerals = json.load(file)
        for mineral in minerals:
            try:
                with transaction.atomic():
                    fields = make_mineral_dict(mineral)
                    Mineral(
                        name=fields['name'],
                        image_filename=fields['image filename'],
                        image_caption=fields['image caption'],
                        category=fields['category'],
                        formula=fields['formula'],
                        strunz_classification=fields['strunz classification'],
                        crystal_system=fields['crystal system'],
                        unit_cell=fields['unit cell'],
                        color=fields['color'],
                        crystal_symmetry=fields['crystal symmetry'],
                        cleavage=fields['cleavage'],
                        mohs_scale_hardness=fields['mohs scale hardness'],
                        luster=fields['luster'],
                        streak=fields['streak'],
                        diaphaneity=fields['diaphaneity'],
                        optical_properties=fields['optical properties'],
                        refractive_index=fields['refractive index'],
                        crystal_habit=fields['crystal habit'],
                        specific_gravity=fields['specific gravity']
                    ).save()

            except IntegrityError:
                continue


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_minerals_to_database)
    ]
