# Generated by Django 2.1 on 2018-08-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0005_auto_20180829_1352'),
        ('minerals', '0004_auto_20180526_1706'),
    ]

    operations = [
    ]
